FROM node:lts-alpine3.14

ENV TZ='Europe/Paris'

RUN apk update && apk add --no-cache npm

WORKDIR /frontend

RUN npm install -g create-react-app@latestt
RUN npm install -D react-router-dom@latest

EXPOSE 3000

ENTRYPOINT npm run build && npm run start